name: absence_manager
description: "A Flutter application to manage and display employee absences."

publish_to: 'none'
version: 1.3.2+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter_bloc: ^9.1.0

  # For value-based equality in Bloc states/events
  equatable: ^2.0.7

  http: ^1.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  path_provider: ^2.1.5
  share_plus: ^10.1.4

  # Replacement for deprecated dart:html - provides web APIs that work across all platforms
  universal_html: ^2.2.4
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  bloc_test: ^10.0.0

  # Use this command to run the code generator for models:
  # dart run build_runner build --delete-conflicting-outputs
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  hive_generator: ^2.0.1

dependency_overrides:
  # Solve conflicts between json_serializable and hive_generator
  source_gen: ^2.0.0

flutter:
  uses-material-design: true
